### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [sommerc/napari-correct-drift#2]
Hello @sommerc,

While working on https://github.com/conda-forge/napari-correct-drift-feedstock/pull/1

We noticed:

The following packages are declared as a dependency but not used in source code
- magicgui

The following packages are NOT declared as a dependency and are used in source code
- pandas 
- scikit-image
- scipy

Could this be amended for the next release?

Cheers 🚀 !

**Comment by sommerc** [comment]
Yes, I'll update it soon! Thanks for the notice. C
